#ifndef NORMALDISPLAY_GLOBAL_H
#define NORMALDISPLAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NORMALDISPLAY_LIBRARY)
#  define NORMALDISPLAYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NORMALDISPLAYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NORMALDISPLAY_GLOBAL_H
